
server:
    port: 9090
spring:
  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/crud
     username: root 
     password: root

  jpa:
    ddl-auto: update
    generate-ddl: true 
    show-sql: true
    
  cache:
     cache-names: users
     ehcache:
      config:
       classpath:ehcache.xml